django06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movie.urls")),
]

movie/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.list, name="list"),
    path("create/", views.create, name="create"),
    path("<int:id>/", views.detail, name="detail"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    ]

movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):

    title = models.CharField(max_length=100)
    audience = models.IntegerField()
    genre = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    

movie/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

movie/views.py
from django.shortcuts import render, redirect
from .forms import MovieForm
from .models import Movie

# Create your views here.
def list(request):
    movies = Movie.objects.all()
    return render(request, "movie/list.html",{"movies":movies})
    
def create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:list")
        else:
            form = MovieForm()
    else:
        form = MovieForm()
    return render(request, 'movie/form.html', {"form":form})
    
def detail(request, id):
    movie = Movie.objects.get(id=id)
    return render(request, 'movie/detail.html', {'movie':movie})

def update(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect("movies:list")
    else:
        form = MovieForm(instance=movie)
    return render(request, 'movie/form.html',{'form':form})
    
def delete(request,id):
    movie = Movie.objects.get(id=id)
    movie.delete()
    return redirect("movies:list")

movie/templates/movie/_movie.html
<div class="card my-3">
    <div class="card-body">
        <div class="card-body">
            <a class="card-text" href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a><span class="badge badge-secondary">{{movie.score}}</span>
        </div>
    </div>
</div>

movie/templates/movie/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{movie.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">누적 관객수 : {{movie.audience}}</h6>
            <p class="card-text">장르 : {{movie.genre}}</p>
            <p class="card-text">평점 : {{movie.score}}</p>
            <p class="card-text">포스터 : {{movie.poster_url}}</p>
            <p class="card-text">영화 소개 : {{movie.description}}</p>
            <div class="d-flex justify-content-end">
                <a href="{% url 'movies:list' %}" class="card-link">목록</a>
                <a href="{% url 'movies:update' movie.id %}" class="card-link">수정</a>
                <a href="{% url 'movies:delete' movie.id %}" class="card-link">삭제</a>
            </div>
        </div>
    </div>
{% endblock %}

movie/templates/movie/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"/>
    </form>
{% endblock %}

movie/templates/movie/list.html
{% extends 'base.html' %}
{% block body %}
    {% for movie in movies %}
        {% include 'movie/_movie.html' %}
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="{% url 'movies:list' %}">
            Movie
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:create' %}">New</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
    
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>